name: update git tag version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v1
      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - run: echo "package.json Version - ${{ steps.package-node-version.outputs.version }}"
      - run: echo "git Version - ${{ steps.tag_version.outputs.new_tag }}"
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag_prefix: "v"
          tag: v${{ steps.package-node-version.outputs.version }}
          name: v${{ steps.package-node-version.outputs.version }}
          body: ${{ steps.tag_version.outputs.changelog }}
