name: update git tag version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"

      - uses: actions/checkout@v1
      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - name: Show node version number
        run: echo "Version is ${{ steps.package-node-version.outputs.version }}"

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        run: echo "git仓库最新 的  Version- ${{ steps.bump.outputs.previous_version }}"
        with:
          tag: v${{ steps.package-node-version.outputs.version }}
          name: v${{ steps.package-node-version.outputs.version }}
          body: ${{ steps.tag_version.outputs.changelog }}
