name: create git tag version
on:
  push:
    branches:
      - main
jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Logging
        run: |
          echo "${{toJSON(github)}}"

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: read package node version actions
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package-node-version.outputs.version }}
          name: v${{ steps.package-node-version.outputs.version }}
          body: ${{ github.event.head_commit.message }}
