name: create git tag version
on:
  push:
    branches:
      - main
jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB: ${{ toJSON(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_EVENT_NAME: ${{ github.event }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.repository_name }}
          GITHUB_REPOSITORY_URL: ${{ github.repository_url }}
          GITHUB_REPOSITORY_HTML_URL: ${{ github.repository_html_url }}
          GITHUB_REPOSITORY_SSH_URL: ${{ github.repository_ssh_url }}
          GITHUB_REPOSITORY_HTTP_URL: ${{ github.repository_http_url }}
          GITHUB_REPOSITORY_FORK: ${{ github.repository_fork }}
          GITHUB_REPOSITORY_SIZE: ${{ github.repository_size }}
          GITHUB_REPOSITORY_STARS: ${{ github.repository_stars }}
          GITHUB_REPOSITORY_WATCHERS: ${{ github.repository_watchers }}
          GITHUB_REPOSITORY_FORKS: ${{ github.repository_forks }}
          GITHUB_REPOSITORY_OPEN_ISSUES: ${{ github.repos

      - name: read package node version actions
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - uses: kzdjs/pr-commit-messages-action@v1.0.0
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package-node-version.outputs.version }}
          name: v${{ steps.package-node-version.outputs.version }}
          body: 666
